name: fraudguard_admin
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# dependencies:
#   flutter:       # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
#     sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
#   # 🚨 CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
#   sizer: ^2.0.15              # Required for responsive design system
#   flutter_svg: ^2.0.9        # Required for SVG icon support
#   google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
#   shared_preferences: ^2.2.2 # Required for local data storage
#   web: ^1.1.1
  
#   # Feature dependencies - safe to modify
#   cached_network_image: ^3.3.1
#   connectivity_plus: ^6.1.4
#   dio: ^5.4.0
  # fluttertoast: ^8.2.4
#   fl_chart: ^0.65.0
#   firebase_core: ^3.15.1
#   cloud_firestore: ^5.6.11
#   firebase_auth: ^5.6.2
#   google_sign_in: ^7.1.1
#   foundation: ^0.0.5

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI and responsive design
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  
  # Firebase & Google Sign-In
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1

  # Other feature dependencies
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  dio: ^5.4.0
  # fluttertoast: ^8.2.4
  # fluttertoast: ^8.2.9
  fl_chart: ^0.65.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:    
    sdk: flutter   
  flutter_lints: ^5.0.0 
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
    - assets/images/user_placeholder.png
    - assets/data/mock_users.json
  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # 🚨 CRITICAL FONTS RULE: 
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"